#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ ! -f .plan ]]; then
    echo "ERROR: no .plan found" 1>&2
    return 1
  fi

  terraform validate
  if terraform apply -auto-approve=true .plan "$@"; then
    rm -f .plan
  fi
}

source sub "$BASH_SOURCE" "$@"
