#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  tf update
  tf validate -check-variables=false
}

source sub "$BASH_SOURCE" "$@"
