#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local prefix="${1:+${1}_}"

  tf output -json -no-color | jq --arg prefix "$prefix" -r 'to_entries[] | "\($prefix)\(.key)=\([.value.value] | flatten | map(select(type | . != "object")) | join(" ") | @sh)"'
}

source sub "$BASH_SOURCE" "$@"
