#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  find . -name '*.tf' -o -name '*.tfvars' | runmany 8 'terraform fmt $1' 
  find . -name '*.json' | runmany 8 'cat $1 | jq . > $1.tmp && mv $1.tmp $1' 
}

source sub "$BASH_SOURCE" "$@"
