#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  mkdir -p .terraform
  rm -rf .terraform/modules
  terraform init "$@"
}

source sub "$BASH_SOURCE" "$@"
