#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  terraform get
  terraform validate
  terraform plan -no-color -out .plan "$@"
  if [[ "$(terraform show .plan)" == "This plan does nothing." ]]; then
    rm -f .plan
  fi
}

source sub "$BASH_SOURCE" "$@"
