#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  tf init -backend=false -get=true -get-plugins=true -upgrade=true
}

source sub "$BASH_SOURCE" "$@"
