#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_wtf="0.0.1"
  jq -n --arg wtf "$ver_wtf" '{wtf: $wtf}'
}

version "$@"
